server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smallurl
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
